// <auto-generated />
using LoadUpdatingTool.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoadUpdatingTool.Migrations
{
    [DbContext(typeof(LoadContext))]
    [Migration("20211127141744_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LoadUpdatingTool.Data.Entity.ServicePoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("gid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConversationInfo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CONVERSION_INFO");

                    b.Property<string>("ServicePointName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IDENTIFICATION");

                    b.HasKey("Id");

                    b.ToTable("ServicePoints");
                });
#pragma warning restore 612, 618
        }
    }
}
